services:
  - type: web
    name: cosmos-drive-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: FIREBASE_TYPE
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_AUTH_URI
        sync: false
      - key: FIREBASE_TOKEN_URI
        sync: false
      - key: FIREBASE_AUTH_PROVIDER_CERT_URL
        sync: false
      - key: FIREBASE_CLIENT_CERT_URL
        sync: false
      - key: PORT
        value: 3001