services:
  - type: web
    name: cosmos-drive-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: PORT
        value: 3001